name: Security Code Scanner - Semgrep
description: 'Runs a Semgrep scan on a repository and uploads the results to GitHub'

inputs:
  paths_ignored:
    description: 'List of paths or patterns to ignore'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Semgrep
      run: |
        pip install semgrep
      shell: bash

    - name: Generate .semgrepignore
      run: |
        echo ".security-scanner/" > .semgrepignore
        echo "${{ inputs.paths_ignored }}" >> .semgrepignore
        cat .semgrepignore
      shell: bash

    - name: Run Semgrep Scan
      run: |
        semgrep --config ${{ github.action_path }}/rules/src --output semgrep-results.sarif --sarif --verbose
      shell: bash
      continue-on-error: true

    - name: Upload Semgrep Results to GitHub
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: semgrep-results.sarif
        checkout_path: ${{ github.workspace }}
